# Generated by Django 5.2.17 on 2026-10-05 04:15

import django.db.models.deletion
from django.db import migrations, models


def require_empty_registry(apps, schema_editor):
    # This migration deliberately replaces the pre-MVP schema, not populated data.
    for name in ("Region", "House", "Organization", "HouseVersion", "ImportRun",
                 "AdministrativeAppointment"):
        model = apps.get_model("registry", name)
        if model.objects.using(schema_editor.connection.alias).exists():
            raise RuntimeError(
                "Миграция MVP-1 требует пустых таблиц registry; нужен отдельный перенос данных."
            )


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(require_empty_registry, migrations.RunPython.noop),
        migrations.CreateModel(
            name='HouseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_method', models.CharField(choices=[('management_company', 'Управляющая организация'), ('hoa_tsn', 'ТСЖ или ТСН'), ('housing_cooperative', 'ЖСК или ЖК'), ('direct', 'Непосредственное управление'), ('not_selected', 'Способ управления не выбран'), ('other', 'Иной способ'), ('unknown', 'Не определено')], default='unknown', max_length=32, verbose_name='Способ управления')),
                ('management_basis', models.CharField(choices=[('owners_decision', 'Выбор собственниками'), ('developer_contract', 'Договор с застройщиком'), ('municipal_competition', 'Муниципальный конкурс'), ('administrative_appointment', 'Назначение администрацией'), ('unknown', 'Основание не определено')], default='unknown', max_length=32, verbose_name='Основание управления')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Начало управления')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Окончание управления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('source', models.CharField(choices=[('gis_search', 'Региональная поисковая выдача ГИС ЖКХ'), ('gis_detail', 'Подробная карточка дома'), ('license_registry', 'Реестр лицензий'), ('administrative_registry', 'Реестр назначений администрации'), ('manual', 'Ручное внесение')], max_length=32, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Период управления',
                'verbose_name_plural': 'Периоды управления',
                'ordering': ('house', '-created_at'),
            },
        ),
        migrations.RemoveField(
            model_name='administrativeappointment',
            name='house',
        ),
        migrations.RemoveField(
            model_name='administrativeappointment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='administrativeappointment',
            name='region',
        ),
        migrations.RemoveField(
            model_name='houseversion',
            name='house',
        ),
        migrations.RemoveField(
            model_name='houseversion',
            name='run',
        ),
        migrations.RemoveField(
            model_name='importrun',
            name='region',
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ('address',), 'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.RemoveIndex(
            model_name='house',
            name='house_region_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='house',
            name='house_active_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='house',
            name='house_method_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='house',
            name='house_oktmo_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='org_ogrn_inn_idx',
        ),
        migrations.RemoveField(
            model_name='house',
            name='active',
        ),
        migrations.RemoveField(
            model_name='house',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='house',
            name='building_year',
        ),
        migrations.RemoveField(
            model_name='house',
            name='consecutive_missing_runs',
        ),
        migrations.RemoveField(
            model_name='house',
            name='detail_hash',
        ),
        migrations.RemoveField(
            model_name='house',
            name='detail_payload',
        ),
        migrations.RemoveField(
            model_name='house',
            name='fias_house_guid',
        ),
        migrations.RemoveField(
            model_name='house',
            name='first_seen_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_condition',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_type_code',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_type_name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='last_missing_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='last_seen_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='locality_name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='management_end_date',
        ),
        migrations.RemoveField(
            model_name='house',
            name='management_method',
        ),
        migrations.RemoveField(
            model_name='house',
            name='management_method_code',
        ),
        migrations.RemoveField(
            model_name='house',
            name='management_method_name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='management_organization',
        ),
        migrations.RemoveField(
            model_name='house',
            name='management_start_date',
        ),
        migrations.RemoveField(
            model_name='house',
            name='max_floor_count',
        ),
        migrations.RemoveField(
            model_name='house',
            name='min_floor_count',
        ),
        migrations.RemoveField(
            model_name='house',
            name='municipality_name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='needs_detail_refresh',
        ),
        migrations.RemoveField(
            model_name='house',
            name='non_residential_premise_count',
        ),
        migrations.RemoveField(
            model_name='house',
            name='oktmo',
        ),
        migrations.RemoveField(
            model_name='house',
            name='operation_year',
        ),
        migrations.RemoveField(
            model_name='house',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='residential_premise_count',
        ),
        migrations.RemoveField(
            model_name='house',
            name='residential_square',
        ),
        migrations.RemoveField(
            model_name='house',
            name='search_hash',
        ),
        migrations.RemoveField(
            model_name='house',
            name='search_payload',
        ),
        migrations.RemoveField(
            model_name='house',
            name='source_status',
        ),
        migrations.RemoveField(
            model_name='house',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='total_square',
        ),
        migrations.RemoveField(
            model_name='house',
            name='underground_floor_count',
        ),
        migrations.RemoveField(
            model_name='house',
            name='uo_selection_method',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='okopf_code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registry_root_guid',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='source_last_event_date',
        ),
        migrations.RemoveField(
            model_name='region',
            name='federal_district',
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='house',
            name='area_residential',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Жилая площадь в доме'),
        ),
        migrations.AddField(
            model_name='house',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Общая площадь дома'),
        ),
        migrations.AddField(
            model_name='house',
            name='building_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Номер дома, корпус, литер, строение'),
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='house',
            name='commissioning_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год ввода'),
        ),
        migrations.AddField(
            model_name='house',
            name='condition',
            field=models.CharField(blank=True, max_length=128, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='house',
            name='construction_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AddField(
            model_name='house',
            name='district',
            field=models.CharField(blank=True, max_length=255, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='house',
            name='fias_guid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='GUID дома в ФИАС'),
        ),
        migrations.AddField(
            model_name='house',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество этажей'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тип дома'),
        ),
        migrations.AddField(
            model_name='house',
            name='non_residential_premises_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Площадь нежилых помещений'),
        ),
        migrations.AddField(
            model_name='house',
            name='non_residential_premises_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Нежилых помещений'),
        ),
        migrations.AddField(
            model_name='house',
            name='planning_structure_element',
            field=models.CharField(blank=True, max_length=255, verbose_name='Элемент планировочной структуры'),
        ),
        migrations.AddField(
            model_name='house',
            name='residential_premises_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Площадь жилых помещений'),
        ),
        migrations.AddField(
            model_name='house',
            name='residential_premises_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Жилых помещений'),
        ),
        migrations.AddField(
            model_name='house',
            name='settlement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_form',
            field=models.CharField(blank=True, max_length=500, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AlterField(
            model_name='house',
            name='detail_fetched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Подробная карточка получена'),
        ),
        migrations.AlterField(
            model_name='house',
            name='gis_address_guid',
            field=models.CharField(blank=True, max_length=128, verbose_name='Код адреса в ГИС ЖКХ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='gis_guid',
            field=models.UUIDField(unique=True, verbose_name='GUID дома в ГИС ЖКХ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_uid',
            field=models.CharField(blank=True, max_length=64, verbose_name='Идентификатор объекта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='wall_material',
            field=models.CharField(blank=True, max_length=500, verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.CharField(max_length=2000, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='ОГРН/ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Сокращённое наименование'),
        ),
        migrations.AlterField(
            model_name='region',
            name='fias_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='GUID региона по ФИАС'),
        ),
        migrations.AddField(
            model_name='housemanagement',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_periods', to='registry.house', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='housemanagement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_periods', to='registry.organization', verbose_name='Организация'),
        ),
        migrations.DeleteModel(
            name='AdministrativeAppointment',
        ),
        migrations.DeleteModel(
            name='HouseVersion',
        ),
        migrations.DeleteModel(
            name='ImportRun',
        ),
        migrations.AddConstraint(
            model_name='housemanagement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('house',), name='one_active_management_per_house'),
        ),
        migrations.AddConstraint(
            model_name='housemanagement',
            constraint=models.CheckConstraint(condition=models.Q(('date_start__isnull', True), ('date_finish__isnull', True), ('date_finish__gte', models.F('date_start')), _connector='OR'), name='management_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='housemanagement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('management_method', 'direct'), _negated=True), ('organization__isnull', True), _connector='OR'), name='direct_management_no_organization'),
        ),
        migrations.AddConstraint(
            model_name='housemanagement',
            constraint=models.CheckConstraint(condition=models.Q(('management_method__in', ['management_company', 'hoa_tsn', 'housing_cooperative', 'direct', 'not_selected', 'other', 'unknown'])), name='management_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='housemanagement',
            constraint=models.CheckConstraint(condition=models.Q(('management_basis__in', ['owners_decision', 'developer_contract', 'municipal_competition', 'administrative_appointment', 'unknown'])), name='management_basis_valid'),
        ),
        migrations.AddConstraint(
            model_name='housemanagement',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['gis_search', 'gis_detail', 'license_registry', 'administrative_registry', 'manual'])), name='management_source_valid'),
        ),
    ]
